# Generated by Django 5.1.1 on 2024-09-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtitle",
            name="language",
            field=models.CharField(default="und", max_length=50),
        ),
    ]
