# Generated by Django 5.1.1 on 2024-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_subtitle_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="subtitle",
            name="timestamp_end",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="subtitle",
            name="timestamp_start",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="videos.language"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subtitle",
            unique_together={("video", "language", "timestamp_start")},
        ),
        migrations.RemoveField(
            model_name="subtitle",
            name="timestamp",
        ),
    ]
